import bot
gecko = bot.Gecko(display=True)
gecko.openClient()
gecko.readScope(path='scope.json')
gecko.visitPage(gecko.scope['home'])
gecko.selectDepartment(tunnel=4)
gecko.selectLocation(city='C', area='C03')
gecko.selectDate(interval=((101, 1), (112, 7)))
gecko.startRetrieval()
gecko.closeClient()